<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NugetAudit>true</NugetAudit>
    <NugetAuditMode>all</NugetAuditMode>
    <NugetAuditLevel>low</NugetAuditLevel>
    <WarningsAsErrors>$(WarningsAsErrors);NU1506</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.298" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="Ookii.Dialogs.WinForms" Version="4.0.0" />
    <PackageVersion Include="Simple.CredentialManager" Version="1.0.0" />
    <PackageVersion Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>
</Project>
