name: FreeRDP Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  # only allowed to read source code (ref. https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)
  contents: read

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    # Build
    - name: build project
      run: dotnet build -c Release src/RoyalApps.Community.FreeRdp.WinForms/RoyalApps.Community.FreeRdp.WinForms.csproj
      env:
        Configuration: ${{ matrix.configuration }}

    # Pack nuget package
    - name: dotnet pack
      run: dotnet pack --no-build -c Release src/RoyalApps.Community.FreeRdp.WinForms/RoyalApps.Community.FreeRdp.WinForms.csproj -o .
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload packages
    - name: Upload managed components
      uses: actions/upload-artifact@v7
      with:
        name: FreeRdp-nupkg
        path: ./*.nupkg

    # Push nuget package to nuget.org
    - name: nuget push
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      env:
        Configuration: ${{ matrix.configuration }}
